name: Build DropKnife Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # CSSharp 插件通常需要 .NET 8

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DropKnife-Plugin
        path: bin/Release/net8.0/DropKnife.dll
